name: mmeslay
description: "Mmeslay ad aruÉ£"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'





dependencies:
  dropdown_button2: ^2.0.0
  flutter:
    sdk: flutter
  cancellation_token_http: ^1.3.0
  intl: ^0.18.0
  lottie: ^2.3.0
  path_provider: ^2.0.14
  record: ^4.4.4
  http_parser: ^4.0.0
  json_theme: ^6.0.0
  logger: ^1.1.0
  permission_handler: ^10.3.0
  slide_countdown: ^0.6.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  rename_app_plus: ^1.2.1
  flutter_launcher_icons: "^0.13.1"



flutter_launcher_icons:
  android: 
    generate : true
    adaptive_icon_foreground : true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 16 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/

